# Generated by Django 2.2.24 on 2021-06-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymoususer',
            options={'ordering': ('-date_created',), 'verbose_name': 'AnonymousUser', 'verbose_name_plural': 'AnonymousUser'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_created',)},
        ),
    ]
