# Generated by Django 2.2.24 on 2021-06-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210620_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_link', to='accounts.DeviceTracker'),
        ),
    ]
