# Generated by Django 2.2.24 on 2021-06-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_anonymoususer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
