# Generated by Django 2.2.24 on 2021-06-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210620_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device',
        ),
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.ManyToManyField(related_name='device_link', to='accounts.DeviceTracker'),
        ),
    ]
