# Generated by Django 2.2.24 on 2021-06-17 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210617_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='anonymoususer',
            name='session_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Session ID'),
        ),
    ]
