# Generated by Django 2.2.24 on 2021-06-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210620_1608'),
        ('blog', '0004_auto_20210618_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='anonymous_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_anonymous_user', to='accounts.DeviceTracker'),
        ),
    ]
