# Generated by Django 2.2.24 on 2021-06-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210620_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_anonymous_user', to='accounts.DeviceTracker'),
        ),
    ]
