# Generated by Django 2.2.24 on 2021-07-21 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210620_1623'),
        ('blog', '0007_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_post', to='accounts.DeviceTracker'),
        ),
    ]
