# Generated by Django 2.2.24 on 2021-07-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210620_1623'),
        ('blog', '0008_post_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='device',
        ),
        migrations.CreateModel(
            name='PostDeviceTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.ManyToManyField(to='accounts.DeviceTracker')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_device_tracker', to='blog.Post')),
            ],
        ),
    ]
