# Generated by Django 2.2.24 on 2021-07-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210721_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_archived',
            new_name='date_deleted',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='archived',
            new_name='deleted',
        ),
    ]
